---
# Akash SDL — Deploy a static HTML page via nginx
#
# TWO OPTIONS:
#
# OPTION A (Recommended): Custom Docker image with HTML baked in
#   1. Build: docker build -t <your-dockerhub-username>/akash-student-ambassador .
#   2. Push:  docker push <your-dockerhub-username>/akash-student-ambassador
#   3. Set the image field below to: <your-dockerhub-username>/akash-student-ambassador
#
# OPTION B: Pull HTML from GitHub at container startup (no Docker Hub needed)
#   1. Push index.html to the main branch of this repo
#   2. Set HTML_URL to:
#      https://raw.githubusercontent.com/brewsterdrinkwater/-akash-ambassador-contributions-technical/main/index.html
#   3. Uncomment the env + command blocks below and remove the OPTION A image line

version: "2.0"

services:
  web:
    # --- OPTION A: Replace with your Docker Hub image after building and pushing ---
    image: nginx:alpine

    # --- OPTION B: Uncomment below to fetch HTML from GitHub at startup ---
    # env:
    #   - HTML_URL=https://raw.githubusercontent.com/brewsterdrinkwater/-akash-ambassador-contributions-technical/main/index.html
    # command:
    #   - sh
    #   - -c
    #   - |
    #     apk add --no-cache curl &&
    #     mkdir -p /usr/share/nginx/html &&
    #     curl -fsSL "$HTML_URL" -o /usr/share/nginx/html/index.html &&
    #     nginx -g 'daemon off;'

    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
