---
version: "2.0"

services:
  web:
    image: nginx:alpine
    env:
      - HTML_URL=https://raw.githubusercontent.com/brewsterdrinkwater/-akash-ambassador-contributions-technical/claude/akash-html-container-WDjDn/index.html
    command:
      - sh
      - -c
      - |
        apk add --no-cache curl &&
        mkdir -p /usr/share/nginx/html &&
        curl -fsSL "$HTML_URL" -o /usr/share/nginx/html/index.html &&
        nginx -g 'daemon off;'
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 256Mi
        storage:
          size: 512Mi
  placement:
    dcloud:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
      pricing:
        web:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
